name: pybrain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - pip
  - pytest
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - swig
  - traits
  - dipy
  - bokeh
  - holoviews
  - plotly
  - pip:
    - atlasreader
    - datalad[full]
    - duecredit
    - fury
    - keras
    - nbval
    - nibabel
    - niflow-nipype1-workflows
    - nilearn
    - nipy
    - nipype
    - nistats
    - nitime
    - nose
    - pingouin
    - pybids
    - pymvpa2
    - tensorflow
    - vtk
